[2025-04-18T07:32:57.595+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T07:32:57.600+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: triphobo_tours_pipeline.geocode_tours manual__2025-04-18T07:32:54.412074+00:00 [queued]>
[2025-04-18T07:32:57.603+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: triphobo_tours_pipeline.geocode_tours manual__2025-04-18T07:32:54.412074+00:00 [queued]>
[2025-04-18T07:32:57.603+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-18T07:32:57.608+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): geocode_tours> on 2025-04-18 07:32:54.412074+00:00
[2025-04-18T07:32:57.611+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2030) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-18T07:32:57.612+0000] {standard_task_runner.py:72} INFO - Started process 2031 to run task
[2025-04-18T07:32:57.612+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'triphobo_tours_pipeline', 'geocode_tours', 'manual__2025-04-18T07:32:54.412074+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/itinerary_tours_dag.py', '--cfg-path', '/tmp/tmpuu586ado']
[2025-04-18T07:32:57.613+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask geocode_tours
[2025-04-18T07:32:57.630+0000] {task_command.py:467} INFO - Running <TaskInstance: triphobo_tours_pipeline.geocode_tours manual__2025-04-18T07:32:54.412074+00:00 [running]> on host 68d96c644388
[2025-04-18T07:32:57.655+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='triphobo_tours_pipeline' AIRFLOW_CTX_TASK_ID='geocode_tours' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T07:32:54.412074+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T07:32:54.412074+00:00'
[2025-04-18T07:32:57.656+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-18T07:32:57.661+0000] {itinerary_tours_dag.py:403} INFO - Processing file from /tmp/triphobo_data/cleaned_tours.csv to /tmp/triphobo_data/tours_with_coords.csv
[2025-04-18T07:32:57.705+0000] {itinerary_tours_dag.py:346} INFO - Total tours to process: 1049
[2025-04-18T07:32:57.705+0000] {itinerary_tours_dag.py:371} INFO - Processing batch 1: rows 1 to 50
[2025-04-18T07:32:57.705+0000] {itinerary_tours_dag.py:399} ERROR - Error processing CSV: name 'extract_place_from_url' is not defined
Traceback (most recent call last):
  File "/opt/airflow/dags/itinerary_tours_dag.py", line 375, in process_csv_in_batches
    place_name = extract_place_from_url(row.get('URL', ''))
                 ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'extract_place_from_url' is not defined
[2025-04-18T07:32:57.708+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/itinerary_tours_dag.py", line 404, in add_coordinates_to_csv
    process_csv_in_batches(input_path, output_path, batch_size=50)
  File "/opt/airflow/dags/itinerary_tours_dag.py", line 375, in process_csv_in_batches
    place_name = extract_place_from_url(row.get('URL', ''))
                 ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'extract_place_from_url' is not defined
[2025-04-18T07:32:57.713+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=triphobo_tours_pipeline, task_id=geocode_tours, run_id=manual__2025-04-18T07:32:54.412074+00:00, execution_date=20250418T073254, start_date=20250418T073257, end_date=20250418T073257
[2025-04-18T07:32:57.717+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-18T07:32:57.718+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 66 for task geocode_tours (name 'extract_place_from_url' is not defined; 2031)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/itinerary_tours_dag.py", line 404, in add_coordinates_to_csv
    process_csv_in_batches(input_path, output_path, batch_size=50)
  File "/opt/airflow/dags/itinerary_tours_dag.py", line 375, in process_csv_in_batches
    place_name = extract_place_from_url(row.get('URL', ''))
                 ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'extract_place_from_url' is not defined
[2025-04-18T07:32:57.752+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-18T07:32:57.759+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T07:32:57.761+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
